"use client";

import Link from "next/link";
import { useEffect, useState, useCallback, useMemo } from "react";
import { Search, CheckCircle2, ExternalLink, Anchor, Users, XCircle, Loader2 } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

type Reservation = { id: string; status: string; total_price: number; passenger_count: number; lead_passenger_name: string; created_at: string; availability?: { date?: string; departure_time?: string; vessel?: { name?: string } | null; route?: { name?: string } | null } | null; vouchers?: { qr_code_token?: string }[] | null };

export default function AgencyReservationsPage() {
  const [rows, setRows] = useState<Reservation[]>([]); const [loading, setLoading] = useState(true); const [working, setWorking] = useState<string | null>(null); const [error, setError] = useState("");
  const supabase = useMemo(() => createClient(), []);
  const load = useCallback(async () => { setLoading(true); setError(""); const { data, error: queryError } = await supabase.from("reservations").select("id,status,total_price,passenger_count,lead_passenger_name,created_at,availability:availability(date,departure_time,vessel:vessels(name),route:routes(name)),vouchers:vouchers(qr_code_token)").order("created_at", { ascending: false }); if (queryError) setError("No se pudieron cargar las reservas."); else setRows((data ?? []) as unknown as Reservation[]); setLoading(false); }, [supabase]);
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, [load]);
  async function cancel(id: string) { if (!window.confirm("¿Cancelar esta reserva? Los cupos volverán a estar disponibles.")) return; setWorking(id); setError(""); const { error: rpcError } = await supabase.rpc("cancel_reservation", { p_reservation_id: id }); if (rpcError) setError("No se pudo cancelar la reserva. Puede que ya haya sido cancelada."); else await load(); setWorking(null); }
  return <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
    <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-8"><div><h1 className="text-3xl font-black tracking-tight text-slate-900 dark:text-white">Mis Reservas</h1><p className="text-slate-500 dark:text-slate-400 mt-1">Historial real de reservas de tu agencia.</p></div><Link href="/agency" className="group flex items-center justify-center gap-2 px-5 py-3 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl font-semibold shadow-sm hover:shadow-md hover:-translate-y-0.5 transition-all duration-300"><Search className="w-5 h-5 transition-transform group-hover:scale-110" />Nueva búsqueda</Link></div>
    {error && <div role="alert" className="mb-5 p-4 rounded-xl bg-red-50 dark:bg-red-950/30 text-red-700 dark:text-red-300 border border-red-100 dark:border-red-900/50">{error}</div>}
    {loading ? <div className="py-20 text-center"><Loader2 className="w-8 h-8 mx-auto animate-spin text-primary" /><p className="mt-3 text-sm text-slate-500 dark:text-slate-400">Cargando reservas…</p></div> : rows.length === 0 ? <div className="py-20 px-6 text-center text-slate-500 dark:text-slate-400 bg-white dark:bg-slate-900 rounded-3xl border border-slate-200 dark:border-slate-800"><CalendarEmpty /><p className="mt-4 font-bold text-slate-900 dark:text-white">Todavía no tienes reservas.</p><p className="text-sm mt-1">Las reservas que confirmes aparecerán aquí.</p></div> : <div className="space-y-4">{rows.map(res => { const voucher = res.vouchers?.[0]?.qr_code_token; const cancelled = res.status === "cancelled"; return <div key={res.id} className="bg-white dark:bg-slate-900 rounded-2xl p-5 border border-slate-200 dark:border-slate-800 shadow-sm hover:shadow-lg hover:-translate-y-0.5 transition-all duration-300 flex flex-col lg:flex-row gap-6 lg:items-center">
      <div className="lg:w-48 shrink-0"><p className="text-xs font-bold text-slate-400 uppercase tracking-wider">Código</p><p className="font-mono font-bold truncate text-slate-800 dark:text-slate-200 mt-1" title={res.id}>{res.id}</p><span className={`inline-flex mt-3 items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-bold ${cancelled ? "bg-red-100 dark:bg-red-950/40 text-red-700 dark:text-red-300" : "bg-emerald-100 dark:bg-emerald-950/40 text-emerald-700 dark:text-emerald-300"}`}>{cancelled ? <XCircle className="w-4 h-4" /> : <CheckCircle2 className="w-4 h-4" />}{cancelled ? "Cancelada" : "Confirmada"}</span></div>
      <div className="flex-1 grid sm:grid-cols-2 gap-4"><div><p className="text-sm font-bold text-primary flex items-center gap-2"><Anchor className="w-4 h-4" />{res.availability?.vessel?.name || "Embarcación"}</p><p className="text-lg font-bold text-slate-900 dark:text-white mt-1">{res.availability?.route?.name || "Ruta"}</p><p className="text-sm text-slate-500 dark:text-slate-400 mt-1">Salida: {res.availability?.date || "—"} · {res.availability?.departure_time?.slice(0,5) || "—"}</p></div><div className="sm:border-l sm:border-slate-200 dark:sm:border-slate-800 sm:pl-6"><p className="text-xs font-bold text-slate-400 uppercase tracking-wider">Titular & cupos</p><p className="font-bold flex items-center gap-2 mt-1 text-slate-900 dark:text-white"><Users className="w-4 h-4 text-slate-400" />{res.lead_passenger_name || "—"}</p><p className="text-sm text-slate-500 dark:text-slate-400">{res.passenger_count} pasajero(s)</p></div></div>
      <div className="lg:w-52 border-t border-slate-100 dark:border-slate-800 lg:border-t-0 lg:border-l lg:border-slate-200 lg:dark:border-slate-800 pt-4 lg:pt-0 lg:pl-6"><p className="text-xs text-slate-400 uppercase tracking-wider">Total</p><p className="text-2xl font-black text-slate-900 dark:text-white">${Number(res.total_price || 0).toFixed(2)}</p><div className="space-y-2 mt-3">{voucher && !cancelled && <Link href={`/verify/${encodeURIComponent(voucher)}`} target="_blank" className="group flex items-center justify-center gap-2 w-full py-2.5 bg-primary hover:bg-blue-600 text-white rounded-xl font-bold transition-all duration-300 hover:-translate-y-0.5 active:scale-95"><ExternalLink className="w-4 h-4 transition-transform group-hover:scale-110" />Ver voucher</Link>}{!cancelled && <button type="button" disabled={working===res.id} onClick={() => cancel(res.id)} className="w-full py-2.5 bg-red-50 dark:bg-red-950/30 text-red-700 dark:text-red-300 rounded-xl font-bold transition-all duration-300 hover:bg-red-100 dark:hover:bg-red-950/50 active:scale-95 disabled:opacity-60">{working===res.id ? "Cancelando…" : "Cancelar reserva"}</button>}</div></div>
    </div>; })}</div>}
  </div>;
}

function CalendarEmpty() { return <div className="mx-auto w-12 h-12 rounded-2xl bg-slate-100 dark:bg-slate-800 flex items-center justify-center"><Search className="w-5 h-5 text-slate-400" /></div>; }
